# syntax=docker/dockerfile:1
FROM node:20-alpine AS base

ENV PORT=3000

RUN \
  apk --no-cache add --virtual build-dependencies python3 build-base git make g++

WORKDIR /automatisch

# copy the app, note .dockerignore
COPY . /automatisch

RUN cd packages/web && yarn
RUN cd packages/web && yarn build

RUN cd packages/backend && yarn

# FROM base AS web
# ENV CI=false
# # RUN cd packages/web && yarn
# # RUN cd packages/web && yarn build

# FROM base AS api
# # COPY ./packages/backend/.env-example-pw.test ./packages/backend/.env
# RUN cd packages/backend && yarn
# # RUN cd packages/backend && yarn db:migrate
# # RUN cd packages/backend && yarn start

# FROM base AS api-queue
# RUN cd packages/backend && yarn start:worker


RUN \
  rm -rf /usr/local/share/.cache/ && \
  apk del build-dependencies


EXPOSE 3000
